services:
  db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./server
    container_name: django
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports: 
      - "8000:8000"
    volumes: 
      - ./server:/app
    depends_on: 
      - db

  frontend:
    build:
      context: ./client
    container_name: react
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - "${REACT_PORT:-5173}:${REACT_PORT:-5173}"
    depends_on:
      - app

volumes:
  postgres_data:
