services:
  db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  app:
    build:
      context: ./server
    container_name: django
    restart: unless-stopped
    env_file:
      - ./.env.prod
    expose:
      - "8000"
    volumes: 
      - ./server:/app
    depends_on: 
      - db
    networks:
      - webnet

  frontend:
    build:
      context: ./client
    container_name: react
    restart: "no"  # only builds once and exits
    env_file:
      - ./.env.prod
    depends_on:
      - app
    volumes:
      - schedulo_frontend:/usr/share/nginx/html
    networks:
      - webnet

volumes:
  postgres_data:
  schedulo_frontend:

networks:
  webnet:
    external: true
