services:
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: schedulo:latest
    build:
      context: .
    container_name: schedulo
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
      DJANGO_SETTINGS_MODULE: server.settings.prod
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
