# Generated by Django 5.1.3 on 2024-12-14 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_memberpermissions_member_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberpermissions",
            name="workspace_role_id",
        ),
        migrations.AddField(
            model_name="memberpermissions",
            name="workspace_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.workspace",
            ),
        ),
    ]
