# Generated by Django 5.1.3 on 2024-12-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_id_rows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacerole",
            name="name",
            field=models.CharField(default="Unnamed Role", max_length=30),
        ),
    ]
