# Generated by Django 5.1.3 on 2026-03-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_memberpermissions_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberrole",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_roles",
                to="api.workspacemember",
            ),
        ),
    ]
