# Generated by Django 5.1.3 on 2026-03-11 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_memberpermissions_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftrequest",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.workspace",
            ),
        ),
    ]
