# Generated by Django 5.1.3 on 2026-03-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_memberrole_member"),
        ("api", "0011_shiftrequest_workspace"),
    ]

    operations = []
