# Generated by Django 5.1.3 on 2026-03-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_merge_20260331_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrequest",
            name="accepted",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("pending", "Pending"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shiftrequest",
            name="approved",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("pending", "Pending"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
