name: Code linter

on: [push, pull_request]
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        python -m pip install black flake8

    - name: Formatting
      run: |
        cd server
        black --check .

    - name: Linting
      run: |
        cd server
        flake8 .